# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Contact Card' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Contact Card
  pod 'Alamofire', '~> 4.0'
  pod 'Material'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftKeychainWrapper'
  pod 'QRCode'
  pod 'SwiftHEXColors'
  pod 'Fabric'
  pod 'Crashlytics'

end
